src/Entity/Paintings.php
<?php

namespace App\Entity;

use App\Repository\PaintingsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PaintingsRepository::class)]
class Paintings
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length:255)]
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Votre titre doit contenir au moins {{ limit }} caractères',
        maxMessage: 'Votre titre ne doit pas dépasser {{ limit }} caractères',
    )]
    private ?string $title = null;


    #[ORM\Column(length: 120)]
    private ?string $image = null;

    #[ORM\Column]
    private ?bool $is_published = null;

    #[ORM\ManyToOne(inversedBy: 'paintings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?category $category = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(
        min: 50,
        max: 600,
        minMessage: 'Votre description doit contenir au moins {{ limit }} caractères',
        maxMessage: 'Votre description ne peut pas dépasser {{ limit }} caractères',
    )]
    private ?string $description = null;

    #[ORM\Column]
    #[Assert\NotEqualTo(
        value: 0

    )]
    private ?int $Height = null;

    #[ORM\Column]
    #[Assert\NotEqualTo(
        value: 0

    )]
    private ?int $Width = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $CreatedAt = null;

    #[ORM\OneToMany(mappedBy: 'paintings', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }


    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }



    public function isIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(bool $is_published): self
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getCategory(): ?category
    {
        return $this->category;
    }

    public function setCategory(?category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->Height;
    }

    public function setHeight(int $Height): self
    {
        $this->Height = $Height;

        return $this;
    }

    public function getWidth(): ?int
    {
        return $this->Width;
    }

    public function setWidth(int $Width): self
    {
        $this->Width = $Width;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPaintings($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPaintings() === $this) {
                $comment->setPaintings(null);
            }
        }

        return $this;
    }
}

src/Controller/GalleryController.php
<?php

namespace App\Controller;




use App\Entity\Comment;
use App\Entity\Paintings;
use App\Form\CommentType;
use App\Repository\CategoryRepository;
use App\Repository\PaintingsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\BrowserKit\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class GalleryController extends AbstractController{


    #[Route('/gallery', name: 'gallery')]
    public function gallery(PaintingsRepository $paintingsRepository, CategoryRepository $categoryRepository): Response
    {
        $categories = $categoryRepository->findAll();
        $paintings = $paintingsRepository->findAll();

        return $this->render('gallery/paintings.html.twig',
        [
            'categories' => $categories,
            'paintings' => $paintings
        ]);
    }


    /**
     * @param PaintingsRepository $repository
     * @param int $id
     * @return Response
     */
    #[Route('/detail/{id}', name: 'detail')]
    public function detail(PaintingsRepository $repository, int$id):Response
    {
        $paintings =$repository->find($id);
      return $this->render('gallery/detail.html.twig',
      [
          'paintings' => $paintings
      ]);
    }

    /**
     * @param Paintings $paintings
     * @param EntityManagerInterface $manager
     * @param Request $request
     * @return Response
     */
    #[Route('/course/{slug}', name: 'comments')]
    public function comment(Paintings $paintings,EntityManagerInterface $manager, Request $request): Response
    {
        $comment= new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $comment->setUser($this->getUser())
                    ->setPaintings($paintings)
                    ->setCreatedAt(new \DateTimeImmutable());
            $manager->persist($comment);
            $manager->flush();
        }
        return $this->renderForm('gallery/detail.html.twig',[
            'paintings' => $paintings,
            'form' => $form,
        ]);
    }




}

templates/gallery/detail.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <main class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="display-4 my-4">Détail du tableau</h2>
            </div>

            <div class="col-md-4">
                <img src="{{ asset('img/paint/' ~ paintings.image) }}" alt="" class="img-fluid">
            </div>
            <div class="col-md-8">
                <h3 class="display-5">{{ paintings.title|upper }}</h3>
                <h4>{{ paintings.category.name }}</h4>
                <h4>{{ paintings.createdAt|date('d/m/Y') }}</h4>
                <p class="lead">{{ paintings.description }}</p>
                <p><a href="{{ path('gallery') }}" class="btn btn-outline-dark">Retour à la gallery</a></p>
            </div>
        </div>
        <div class="col-md-8 offset-md-2" id="comments">
            {% for comment in paintings.comments %}
                <h5 class="mt-3">{{ comment.title }}</h5>
                <h6>User Name</h6>
                <h6 class="text-muted">Ajouté le&nbsp;{{ comment.createdAt | date('d/m/Y') }}
                    {% for i in 1..5 %}
                        {% if i <= comment.rating %}
                            <i class="icofont-star text-primary"></i>
                        {% else %}
                            <i class="icofont-star text-secondary"></i>
                        {% endif %}
                    {% endfor %}
                </h6>
                <p>{{ comment.comment }}</p>
                <hr>
            {% endfor %}
        </div>
    </main>
{% endblock %}

templates/gallery/paintings.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gallery{% endblock %}

{% block body %}
    <main>
        <div class="album py-5 bg-dark">
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    <div class="col-md-12 controls-filter">
                        <ul>

                            <li data-filter="all" class="btn btn-outline-primary"> All items </li>
                            {% for category in categories %}
                                <li data-filter="{{ category.id }}" class="btn btn-outline-primary"> {{ category.name}} </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col filter-container">
                        {% for painting in paintings %}
                            <div class="col-md-4 filtr-item" data-category="{{ painting.category.id }}" data-sort="value">
                        <div class="card shadow-none">
                            <img src="{{ asset('img/paint/' ~ painting.image) }}" alt="" class="img-fluid">
                            <div class="card-body ">
                                <p>{{ painting.title }}</p>
                                <p>{{ painting.createdAt | date('d/m/Y') }}</p>
                                <p>{{ painting.category.name }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a class="btn btn-sm" href="{{ path('detail', {id:painting.id}) }}">En savoir plus</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div>

    </main>
    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('js/jquery.filterizr.min.js') }}"></script>
    <script>
        let filterizd = $('.filter-container').filterizr({
            // options here
        });
    </script>
{% endblock %}